window.photoTitles = {
  "foto_8.jpg": "Herramientas, objetos y capas de uso",
  "foto_10.jpg": "Memoria impresa sobre el puesto",
  "foto_11.jpg": "Un homenaje entre objetos",
  "foto_12.jpg": "Álbum abierto, historias encontradas",
  "foto_14.jpg": "Religión, relato y papel",
  "foto_15.jpg": "Libros entre pequeños objetos",
  "foto_16.jpg": "Vinilos en cajas de fruta",
  "foto_18.jpg": "Buscar disco por disco",
  "foto_20.jpg": "Antigüedades a ras de calle",
  "foto_21.jpg": "Figuras, imágenes y devoción popular",
  "foto_22.jpg": "El flujo del Rastro",
  "foto_23.jpg": "El vendedor detrás de los discos",
  "foto_24.jpg": "Mesa de hallazgos pequeños",
  "foto_26.jpg": "Un letrero hecho a mano",
  "foto_27.jpg": "Libros, pinturas y santos",
  "foto_28.jpg": "Teatro La Latina como marco urbano",
  "foto_31.jpg": "Puesto frente a Plaza Lavapiés",
  "foto_32.jpg": "Mercado y comercio permanente",
  "foto_34.jpg": "Calle llena hasta el fondo",
  "foto_35.jpg": "Entre ropa y personas",
  "foto_36.jpg": "Una plaza convertida en mercado",
  "foto_37.jpg": "Bolsos bajo un rótulo directo",
  "foto_38.jpg": "Ropa, obra y mercado",
  "foto_39.jpg": "Una ventana abierta hacia la calle",
  "foto_41.jpg": "Bajo sombrillas y árboles",
  "foto_42.jpg": "Descanso en medio del recorrido",
  "foto_43.jpg": "Escaparate de barrio",
  "foto_44.jpg": "La vendedora trabajando",
  "foto_45.jpg": "Conversación a pie de calle",
  "foto_48.jpg": "Reflejos en un escaparate",
  "foto_49.jpg": "Cerámica como mosaico de color",
  "foto_50.jpg": "Cerámica El Rastro",
  "foto_51.jpg": "Paseo bajo los árboles",
  "foto_52.jpg": "Una corriente de visitantes",
  "foto_53.jpg": "Bolsos sobre las cabezas",
  "foto_54.jpg": "El mercado frente a las fachadas",
  "foto_55.jpg": "Cuero, toldos y multitud",
  "foto_56.jpg": "Cruce de miradas en la plaza",
  "foto_57.jpg": "Una pared de vestidos",
  "foto_58.jpg": "Ropa como paisaje",
  "foto_59.jpg": "Colores colgados en la calle",
  "foto_60.jpg": "Vista abierta de la multitud",
  "foto_61.jpg": "El Rastro en perspectiva",
  "foto_63.jpg": "El mercado visto desde arriba",
  "foto_64.jpg": "Una calle lateral del Rastro",
  "foto_65.jpg": "Bolsos sobre una fachada",
  "foto_66.jpg": "Espejos apoyados en la calle",
  "foto_67.jpg": "Reflejos del mercado",
  "foto_69.jpg": "Cristal, cerámica y conversación",
  "foto_70.jpg": "Mesa de antigüedades bajo una lona",
  "foto_72.jpg": "El anticuario sentado entre sus piezas",
  "foto_73.jpg": "Antigüedades Palacios",
  "foto_75.jpg": "Joyas bajo el toldo",
  "foto_76.jpg": "Brillos y pequeñas piezas",
  "foto_77.jpg": "Pulseras, collares y textura",
  "foto_78.jpg": "La mujer detrás del puesto",
  "foto_79.jpg": "Mostrar una pieza",
  "foto_80.jpg": "Cámaras analógicas en azul",
  "foto_81.jpg": "Tecnología de otra época",
  "foto_82.jpg": "El puesto de cámaras completo",
  "foto_85.jpg": "Cámaras, lentes y coleccionismo",
  "foto_87.jpg": "Vaqueros a dos euros",
  "foto_88.jpg": "Comercio que se desborda a la acera",
  "foto_90.jpg": "Cruce de calles y personas",
  "foto_91.jpg": "Una calle en sombra",
  "foto_92.jpg": "Pañuelos, accesorios y mesa negra",
  "foto_93.jpg": "Collares como cortina",
  "foto_94.jpg": "Antigüedades junto a una persiana pintada",
  "foto_98.jpg": "Objetos blancos y conversación",
  "foto_99.jpg": "Negociar alrededor de una mesa",
  "foto_100.jpg": "El anticuario en la puerta",
  "foto_101.jpg": "Metales colgando",
  "foto_103.jpg": "Un pequeño mundo sobre el suelo",
  "foto_104.jpg": "Puesto de objetos antiguos",
  "foto_105.jpg": "Antigüedades frente al comercio",
  "foto_108.jpg": "Muñecas en la calle",
  "foto_109.jpg": "Una pared de muñecas",
  "foto_110.jpg": "El vendedor entre sus muñecas",
  "foto_111.jpg": "Muñecas usadas, cuerpos de memoria",
  "foto_113.jpg": "Cestas llenas de juguetes",
  "foto_114.jpg": "Conversación frente al puesto de muñecas",
  "foto_115.jpg": "Lámparas y objetos decorativos",
  "foto_116.jpg": "Zapatos sobre una mesa",
  "foto_117.jpg": "Flores y comercio de barrio",
  "foto_120.jpg": "Librería Juanito",
  "foto_121.jpg": "Libros que salen a la acera",
  "foto_122.jpg": "Rebuscar bajo la sombra",
  "foto_123.jpg": "Mirar a través de la ventana",
  "foto_125.jpg": "La plaza como cruce",
  "foto_126.jpg": "Bicicleta entre el mercado",
  "foto_127.jpg": "Ropa clara bajo el toldo",
  "foto_128.jpg": "Bolsos y textiles neutros",
  "foto_129.jpg": "Una pared de telas",
  "foto_130.jpg": "Abrigos de piel en fila",
  "foto_131.jpg": "Texturas de piel",
  "foto_132.jpg": "El barrio por encima de los toldos",
  "foto_133.jpg": "Mirar hacia arriba desde la multitud",
  "foto_134.jpg": "Puesto de flores",
  "foto_135.jpg": "Flores como explosión de color",
  "foto_136.jpg": "Descansar al final del recorrido",
};
